# Generated by Django 4.2.2 on 2024-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="public_date",
            field=models.IntegerField(
                blank=True, default=2001, verbose_name="Дата выхода"
            ),
        ),
    ]
