# Generated by Django 4.2.2 on 2024-03-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_book_public_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="public_date",
            field=models.DateField(
                blank=True, default=2001, verbose_name="Дата выхода"
            ),
        ),
    ]
