# Generated by Django 4.2.2 on 2024-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_book_public_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user_ip",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, default=None, max_length=100, verbose_name="Название"
            ),
        ),
    ]
