# Generated by Django 4.2.2 on 2024-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_feedback_user_ip_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="public_date",
            field=models.DateField(
                blank=True, default="2001-01-01", verbose_name="Дата выхода"
            ),
        ),
    ]
