# Generated by Django 4.2.2 on 2024-03-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_book_public_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
