# Generated by Django 4.2.2 on 2024-03-31 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_feedback_user_delete_cart_delete_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time_add",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Время добавления"
            ),
        ),
    ]
